CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Shell via UART
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_LOG_BACKEND=y

# zbus
CONFIG_ZBUS=y

# JSON command parsing
CONFIG_JSON_LIBRARY=y

# Settings
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y

CONFIG_APP_VERSION="1.2.0"
